services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: devsu-account-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pedro123*
    ports:
      - "5432:5432"
    networks:
      - app-network 
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
      
  account-api:
    build:
      context: ./Devsu.AccountManagement.AccountMovement
      dockerfile: Devsu.AccountManagement.AccountMovementServiceAPI/Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DevsuConnection=Host=postgres;Port=5432;Database=devsu-account-management;Username=postgres;Password=Pedro123*;SearchPath=account-movement

  client-api:
    build:
      context: ./Devsu.AccountManagement.ClientPerson
      dockerfile: Devsu.AccountManagement.ClientPersonServiceAPI/Dockerfile
    ports:
      - "5001:80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DevsuConnection=Host=postgres;Port=5432;Database=devsu-account-management;Username=postgres;Password=Pedro123*;SearchPath=client-person

networks:
  app-network:
    driver: bridge